DROP SCHEMA IF EXISTS `ILB`;
CREATE SCHEMA `ILB`;
USE `ILB`;

CREATE TABLE APP_USER (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   SSO_ID VARCHAR(30) NOT NULL,
   PASSWORD VARCHAR(100) NOT NULL,
   FIRST_NAME VARCHAR(30) NOT NULL,
   LAST_NAME  VARCHAR(30) NOT NULL,
   EMAIL VARCHAR(30) NOT NULL,
   PRIMARY KEY (ID),
   UNIQUE (SSO_ID)
);
